version: "3.4"

services:
  mssqlserver:
    image: "csgrimberg/mssqlserver:latest"
    build:
      context: .
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword1234
      - MSSQL_PID=Express
    ports:
      - "0.0.0.0:1433:1433"
    command: ["/opt/mssql/bin/sqlservr"]