name: Build & Publish the SQL Server Engine image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      GH_REGISTRY_USER: ${{ secrets.GH_REGISTRY_USER }}
      GH_REGISTRY_PASSWORD: ${{ secrets.GH_REGISTRY_PASSWORD }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
    
    steps:
    - uses: actions/checkout@v2

    - name: Build local image and Tag
      run: |
        docker build -t csgrimberg/mssqlserver:latest .
        docker tag csgrimberg/mssqlserver:latest docker.pkg.github.com/christiangrimberg/mssqlserver/csgrimberg/mssqlserver:latest

    - name: Run the Container and waiting to start SQL Server Engine
      run: |
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=$SA_PASSWORD' -e 'MSSQL_PID=Express' -p 0.0.0.0:1433:1433 --name mssqlserver -d csgrimberg/mssqlserver:latest
#        docker exec mssqlserver /bin/bash -c /var/opt/mssql/scripts/start-sql-engine.sh
      
    - name: Test connection to Database Engine
      run: |
        docker exec mssqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '$SA_PASSWORD' -Q 'SELECT @@VERSION'
      
    - name: Connect to GitHub Packages with GitHub Secrets
      run: |
        docker login https://docker.pkg.github.com -u $GH_REGISTRY_USER -p $GH_REGISTRY_PASSWORD

    - name: Push the local image to GitHub Packages
      run: |
        docker push docker.pkg.github.com/christiangrimberg/mssqlserver/csgrimberg/mssqlserver:latest

    - name: Connect to DockerHub with GitHub Secrets
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Push the local image to DockerHub
      run: |
        docker push csgrimberg/mssqlserver:latest
