name: Build & Publish Container Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  github-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Connect to GitHub Packages with GitHub Secrets
        env:
          GH_REGISTRY_USER: ${{ secrets.GH_REGISTRY_USER }}
          GH_REGISTRY_PASSWORD: ${{ secrets.GH_REGISTRY_PASSWORD }}
        run: |
          docker login https://docker.pkg.github.com -u $GH_REGISTRY_USER -p $GH_REGISTRY_PASSWORD

      - name: Build local image and Tag
        run: |
          docker build -t csgrimberg/mssqlserver:latest .
          docker tag csgrimberg/mssqlserver:latest docker.pkg.github.com/christiangrimberg/mssqlserver/mssqlserver
      
      - name: Push the local image to GitHub Packages
        run: |
          docker push docker.pkg.github.com/christiangrimberg/mssqlserver/mssqlserver:latest

  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Connect to DockerHub with GitHub Secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build local image
        run: |
          docker build -t csgrimberg/mssqlserver:latest .
      
      - name: Push the local image to DockerHub
        run: |
          docker push csgrimberg/mssqlserver:latest
